In [13]:
# Run the following cell to import utilities

import numpy as np
import time

from utils import State, Action, load_data

In [14]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.linear_model import LinearRegression
from collections import OrderedDict
from torch import tensor
import time

In [15]:
from utilsHJ import localScore
from tfmData import loadData

ImportError: cannot import name 'getLocalScores' from 'utilsHJ' (c:\Users\HJ\Code Projects\CS2109S\ultimate-sudoku\utilsHJ.py)

In [2]:
data = load_data()
assert len(data) == 80000
for state, value in data[:3]:
    print(state)
    print(f"Value = {value}\n\n")

State(
    board=
        0 0 0 | 0 0 0 | 0 0 0
        0 0 0 | 0 0 0 | 0 0 0
        0 0 0 | 1 0 0 | 0 2 0
        ---------------------
        0 0 0 | 0 0 0 | 0 2 1
        0 0 0 | 0 0 2 | 0 1 2
        0 0 0 | 0 0 0 | 0 1 0
        ---------------------
        0 0 0 | 0 0 0 | 0 0 0
        0 0 2 | 0 0 1 | 0 0 0
        0 0 0 | 0 0 0 | 0 0 0, 
    local_board_status=
        [[0 0 0]
         [0 0 0]
         [0 0 0]], 
    prev_local_action=(2, 1), 
    fill_num=2
)

Value = -0.005


State(
    board=
        2 1 0 | 0 0 2 | 0 1 2
        1 0 0 | 2 0 0 | 2 0 0
        2 0 1 | 0 2 2 | 1 0 0
        ---------------------
        2 0 0 | 1 1 0 | 2 0 0
        1 2 1 | 0 0 2 | 0 2 1
        2 0 2 | 0 0 0 | 2 2 0
        ---------------------
        2 1 0 | 1 0 1 | 0 0 1
        1 0 1 | 0 0 0 | 0 1 1
        0 0 0 | 0 0 2 | 0 1 2, 
    local_board_status=
        [[0 0 0]
         [2 0 0]
         [0 0 0]], 
    prev_local_action=(0, 0), 
    fill_num=1
)

Value = 0.376


State(
    bo

In [6]:
transformedData = loadData("tfmData.pkl")
print(len(transformedData))
print(transformedData[:3])

NameError: name 'loadData' is not defined

In [ ]:
print(localScore(data[0][0].board))