In [1]:
# Run the following cell to import utilities

import numpy as np
import time

from utils import State, Action, load_data

In [3]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.linear_model import LinearRegression
from collections import OrderedDict
from torch import tensor
import time

In [4]:
from utilsHJ import localScore

In [2]:
data = load_data()
assert len(data) == 80000
for state, value in data[:3]:
    print(state)
    print(f"Value = {value}\n\n")

State(
    board=
        0 0 0 | 0 0 0 | 0 0 0
        0 0 0 | 0 0 0 | 0 0 0
        0 0 0 | 1 0 0 | 0 2 0
        ---------------------
        0 0 0 | 0 0 0 | 0 2 1
        0 0 0 | 0 0 2 | 0 1 2
        0 0 0 | 0 0 0 | 0 1 0
        ---------------------
        0 0 0 | 0 0 0 | 0 0 0
        0 0 2 | 0 0 1 | 0 0 0
        0 0 0 | 0 0 0 | 0 0 0, 
    local_board_status=
        [[0 0 0]
         [0 0 0]
         [0 0 0]], 
    prev_local_action=(2, 1), 
    fill_num=2
)

Value = -0.005


State(
    board=
        2 1 0 | 0 0 2 | 0 1 2
        1 0 0 | 2 0 0 | 2 0 0
        2 0 1 | 0 2 2 | 1 0 0
        ---------------------
        2 0 0 | 1 1 0 | 2 0 0
        1 2 1 | 0 0 2 | 0 2 1
        2 0 2 | 0 0 0 | 2 2 0
        ---------------------
        2 1 0 | 1 0 1 | 0 0 1
        1 0 1 | 0 0 0 | 0 1 1
        0 0 0 | 0 0 2 | 0 1 2, 
    local_board_status=
        [[0 0 0]
         [2 0 0]
         [0 0 0]], 
    prev_local_action=(0, 0), 
    fill_num=1
)

Value = 0.376


State(
    bo

In [ ]:
print(localScore(data[0][0].board))