In [1]:
# Run the following cell to import utilities

import numpy as np
import time

from utils import State, Action, load_data

In [2]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.linear_model import LinearRegression
from collections import OrderedDict
from torch import tensor
import time

In [3]:
from utilsHJ import localScore
from tfmData import loadData

In [4]:
data = load_data()
assert len(data) == 80000
for state, value in data[:3]:
    print(state)
    print(f"Value = {value}\n\n")

State(
    board=
        0 0 0 | 0 0 0 | 0 0 0
        0 0 0 | 0 0 0 | 0 0 0
        0 0 0 | 1 0 0 | 0 2 0
        ---------------------
        0 0 0 | 0 0 0 | 0 2 1
        0 0 0 | 0 0 2 | 0 1 2
        0 0 0 | 0 0 0 | 0 1 0
        ---------------------
        0 0 0 | 0 0 0 | 0 0 0
        0 0 2 | 0 0 1 | 0 0 0
        0 0 0 | 0 0 0 | 0 0 0, 
    local_board_status=
        [[0 0 0]
         [0 0 0]
         [0 0 0]], 
    prev_local_action=(2, 1), 
    fill_num=2
)

Value = -0.005


State(
    board=
        2 1 0 | 0 0 2 | 0 1 2
        1 0 0 | 2 0 0 | 2 0 0
        2 0 1 | 0 2 2 | 1 0 0
        ---------------------
        2 0 0 | 1 1 0 | 2 0 0
        1 2 1 | 0 0 2 | 0 2 1
        2 0 2 | 0 0 0 | 2 2 0
        ---------------------
        2 1 0 | 1 0 1 | 0 0 1
        1 0 1 | 0 0 0 | 0 1 1
        0 0 0 | 0 0 2 | 0 1 2, 
    local_board_status=
        [[0 0 0]
         [2 0 0]
         [0 0 0]], 
    prev_local_action=(0, 0), 
    fill_num=1
)

Value = 0.376


State(
    bo

In [5]:
transformedData = loadData("tfmData.pkl")
print(len(transformedData))
print(transformedData[:10])

80000
[(array([0.5       , 0.81757448, 0.26894142, 0.5       , 0.26894142,
       0.88079708, 0.26894142, 0.73105858, 0.5       ]), -0.005), (array([0.73105858, 0.00669285, 0.5       , 2.        , 0.81757448,
       0.00669285, 0.81757448, 0.81757448, 0.97068777]), 0.376), (array([0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.73105858, 0.5       , 0.5       , 0.5       ]), 0.026), (array([0.81757448, 0.5       , 0.11920292, 0.5       , 0.95257413,
       0.5       , 0.5       , 0.5       , 0.11920292]), 0.083), (array([0.62245933, 0.5       , 1.        , 0.95257413, 0.62245933,
       0.98201379, 0.07585818, 0.11920292, 2.        ]), 0.116), (array([0.26894142, 0.26894142, 0.04742587, 0.18242552, 0.62245933,
       0.92414182, 0.95257413, 0.5       , 0.88079708]), 0.106), (array([0.26894142, 0.18242552, 0.98901306, 0.62245933, 0.07585818,
       0.73105858, 0.62245933, 0.98201379, 0.04742587]), -0.183), (array([0.11920292, 0.37754067, 0.37754067, 0.37754067, 0.81

In [6]:
from utilsHJ import getLinesImm
grid = np.array(transformedData[5][0]).reshape((3, 3))
linesImm = getLinesImm(grid)
print(linesImm)
transformedData2 = loadData("tfmData2.pkl")
print(linesImm == transformedData2[5][0])

[[0.2689414213699951, 0.2689414213699951, 0.04742587317756678], [0.18242552380635635, 0.6224593312018546, 0.9241418199787566], [0.9525741268224334, 0.5, 0.8807970779778823], [0.2689414213699951, 0.18242552380635635, 0.9525741268224334], [0.2689414213699951, 0.6224593312018546, 0.5], [0.04742587317756678, 0.9241418199787566, 0.8807970779778823], [0.2689414213699951, 0.6224593312018546, 0.8807970779778823], [0.9525741268224334, 0.6224593312018546, 0.04742587317756678]]
True


In [7]:
from utilsHJ import getGlobalLineScores
print(linesImm)
print(getGlobalLineScores(linesImm))

[[0.2689414213699951, 0.2689414213699951, 0.04742587317756678], [0.18242552380635635, 0.6224593312018546, 0.9241418199787566], [0.9525741268224334, 0.5, 0.8807970779778823], [0.2689414213699951, 0.18242552380635635, 0.9525741268224334], [0.2689414213699951, 0.6224593312018546, 0.5], [0.04742587317756678, 0.9241418199787566, 0.8807970779778823], [0.2689414213699951, 0.6224593312018546, 0.8807970779778823], [0.9525741268224334, 0.6224593312018546, 0.04742587317756678]]
[-0.914691284082443, 0.2290266749869675, 0.8333712048003157, -0.09605892800121518, -0.1085992474281503, 0.35236477113420567, 0.272197830549732, 0.12245933120185476]


In [14]:
transformedData3 = loadData("tfmData3.pkl")
print(transformedData3[5])

([-0.914691284082443, 0.2290266749869675, 0.8333712048003157, -0.09605892800121518, -0.1085992474281503, 0.35236477113420567, 0.272197830549732, 0.12245933120185476], 0.106)


In [13]:
transformedData4 = loadData("tfmData4.pkl")
print(transformedData4[5])

([-0.914691284082443, 0.2290266749869675, 0.8333712048003157, -0.09605892800121518, -0.1085992474281503, 0.35236477113420567, 0.272197830549732, 0.12245933120185476], 0.553)


In [39]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [28]:
data = loadData("tfmData4.pkl")

X = np.array([inputs for inputs, _ in data])
y = np.array([target for _, target in data])

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=2109)

In [ ]:
# Linear regression
logReg = LogisticRegression()
logReg.fit(X_train, y_train)
print(f'Training score: {logReg.score(X_train, y_train)}')
print(f'Validation score: {logReg.score(X_test, y_test)}')


In [ ]:
# Logistic regression
logReg = LogisticRegression()
logReg.fit(X_train, y_train)
print(f'Training score: {logReg.score(X_train, y_train)}')
print(f'Validation score: {logReg.score(X_test, y_test)}')

In [49]:
polyreg = make_pipeline(PolynomialFeatures(degree=4), LinearRegression())
polyreg.fit(X_train, y_train)
print(f'Training score: {polyreg.score(X_train, y_train)}')
print(f'Validation score: {polyreg.score(X_test, y_test)}')

Training score: 0.36568519899326135
Validation score: 0.3438515886810909


In [51]:
import torch
import torch.nn as nn
import torch.optim as optim

In [65]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [67]:
y_train = y_train.view(y_train.shape[0], 1)
y_test = y_test.view(y_test.shape[0], 1)

In [56]:
n_features = 8

In [54]:
class LogisticRegressionModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [ ]:
model = LogisticRegressionModel(n_features)
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(len(X_train)):
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 200 == 0:
        print(f"Epoch [{epoch}/{len(X_train)}] Loss: {loss.item():.4f}")



Epoch [0/53600] Loss: 0.7433
Epoch [200/53600] Loss: 0.6646
Epoch [400/53600] Loss: 0.6515
Epoch [600/53600] Loss: 0.6487
Epoch [800/53600] Loss: 0.6478
Epoch [1000/53600] Loss: 0.6475
Epoch [1200/53600] Loss: 0.6473
Epoch [1400/53600] Loss: 0.6471
Epoch [1600/53600] Loss: 0.6470
Epoch [1800/53600] Loss: 0.6469
Epoch [2000/53600] Loss: 0.6468
Epoch [2200/53600] Loss: 0.6468
Epoch [2400/53600] Loss: 0.6467
Epoch [2600/53600] Loss: 0.6466
Epoch [2800/53600] Loss: 0.6466
Epoch [3000/53600] Loss: 0.6466
Epoch [3200/53600] Loss: 0.6466
Epoch [3400/53600] Loss: 0.6465
Epoch [3600/53600] Loss: 0.6465
Epoch [3800/53600] Loss: 0.6465
Epoch [4000/53600] Loss: 0.6465
Epoch [4200/53600] Loss: 0.6465
Epoch [4400/53600] Loss: 0.6465
Epoch [4600/53600] Loss: 0.6465
Epoch [4800/53600] Loss: 0.6465
Epoch [5000/53600] Loss: 0.6464
Epoch [5200/53600] Loss: 0.6464
Epoch [5400/53600] Loss: 0.6464
Epoch [5600/53600] Loss: 0.6464
Epoch [5800/53600] Loss: 0.6464
Epoch [6000/53600] Loss: 0.6464
Epoch [6200/536

In [71]:
# Predictions
with torch.no_grad():
    preds = model(X_test)
    print("Predicted outputs:\n", preds)

Predicted outputs:
 tensor([[0.6176268458],
        [0.4734345675],
        [0.8137833476],
        ...,
        [0.5247956514],
        [0.5873779655],
        [0.4094014168]])


In [70]:
torch.set_printoptions(precision=10)
print(model.state_dict())

OrderedDict({'linear.weight': tensor([[0.1499544531, 0.1596477330, 0.1562808752, 0.1590311676, 0.1475337893,
         0.1440917253, 0.2090526968, 0.1907798499]]), 'linear.bias': tensor([0.0023940571])})


In [ ]:
model.eval()
with torch.no_grad():
    outputs = model(X_test)
    criterionTest = nn.MSELoss()
    print("Test MSE Loss:", loss.item())

    for pred, true in zip(outputs.view(-1), y_test.view(-1)):
        print(f"Predicted: {pred.item():.3f}, Target: {true.item():.3f}")

Test MSE Loss: 0.6464233994483948
